### ISSUE TITLE
Use .desktop files instead

### ISSUE THREAD

**Issue by ghost** [dcousens/dmenu-levenshtein#6]
Not sure if that is possible right now. But it would be great if we had the option to use `.desktop` files instead of the executables.

**Comment by dcousens** [comment]
@wxxn true, perhaps we could make that a `dmenu-script` instead?
Its not really relevant to `dmenu`, maybe `dmenu_run` though.

**Comment by wxxn** [comment]
Maybe. I tried using your version of dmenu with [j4-dmenu-desktop](https://github.com/enkore/j4-dmenu-desktop) which uses `.desktop` files instead, but it didn't work out. It was using the the regular executables.

**Comment by dcousens** [comment]
I'll look into it.

**Comment by dcousens** [comment]
@ghost would they ideally be from `/usr/share/applications/` solely?

**Comment by dcousens** [comment]
Not fixed
